### ISSUE TITLE
Make logical nature of `size` property explicit with `logical` keyword

### ISSUE THREAD

**Issue by potch** [WICG/logical-sizing-properties#1]
Right now, usage of `size` assumes a logical dimension properties. However, `size` would be useful for media and other elements whose dimensions do not change when writing direction changes. I proposed that `size` adopt the optional `logical` keyword for to make it explicit so `size` can be used for media elements:

```css
video {
  margin: logical 1em 0;
  /* note: these are non-logical sizes */
  size: 100px / 50% / 600px calc(16/9);
}

.my-widget {
  margin: logical 1em 0;
  /* opting in to logical sizing */
  size: logical 50% calc(3/2);
}
```
