### ISSUE TITLE
Add a `layout-paradigm` property to set logical vs physical layout for all properties

### ISSUE THREAD

**Issue by potch** [WICG/logical-sizing-properties#2]
Right now, we have the `logical` keyword to opt legacy layout properties into logical layout in a backward-compatible way:

```css
.my-widget {
  margin: 1em .0;
  margin: logical 1em 0;
  padding: .25em .5em;
  padding: logical .25em .5em;
}
```

Let's add a property that applies to all these layout properties to opt them in to the logical model:

```css
.my-widget {
  layout-paradigm: logical;
  margin: 1em .0;
  padding: .25em .5em;
}
```

The proposed values are `layout-paradigm: physical` (which is the initial value), and `layout-paradigm: logical`.

**Comment by jonathanKingston** [comment]
After our quick discussion the spec would also have to account for physical dimensions too, so when I set:

``` css
* {
  layout-paradigm: logical;
}
video {
  padding: physical 20px 10px;
  size: physical 200px calc(2/1);
  margin: 20px 10px;
}
div {
  margin: 10px 20px;
}
```

Which would be the same as setting:

``` css
video {
  padding: 20px 10px;
  aspect-ratio: calc(2/1);
  width: 200px;
  margin: logical 20px 10px;
}
div {
  margin: logical 10px 20px;
}
```
